kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devkdmapps-fileshare-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
