apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nteapps
  namespace: nteapps
  labels:
    app: nte-dev-phasone-app
spec:
  replicas: 2
  selector:
      matchLabels:
        app: nte-dev-phasone-app
  template:
    metadata:
      labels:
        app: nte-dev-phasone-app
    spec:
      containers:
      - name: nte-dev-phasone-app
        image: nginx
        volumeMounts:
        - name: azurefileshare
          mountPath: /usr/share/nginx/html
      volumes:
      - name: azurefileshare
        azureFile:
          secretName: ntesasecretdev
          shareName: ntedevfs
          readOnly: false
